#pragma once
#ifndef __BLINK_ANIMATION_STATE__
#define __BLINK_ANIMATION_STATE__

enum BlinkAnimationState
{
	BLINK_IDLE_UP,
	BLINK_IDLE_DOWN,
	BLINK_IDLE_LEFT,
	BLINK_IDLE_RIGHT,
	BLINK_RUN_UP,
	BLINK_RUN_DOWN,
	BLINK_RUN_RIGHT,
	BLINK_RUN_LEFT,
	BLINK_CLOSE_ATTACK,
	NUM_OF_BLINK_ANIMATION_STATES
};

#endif /* defined (__BLINK_ANIMATION_STATE__)*/