#pragma once
#ifndef __BULLET_ANIMATION_STATE__
#define __BULLET_ANIMATION_STATE__

enum BulletAnimationState
{
	BULLET_RIGHT,
	BULLET_LEFT,
	BULLET_DOWN,
	BULLET_UP,
	NUM_OF_BULLET_ANIMATION_STATES
};

#endif