#pragma once
#ifndef __ENEMY_ANIMATION_STATE__
#define __ENEMY_ANIMATION_STATE__

enum EnemyAnimationStates
{
	ENEMY_IDLE_UP,
	ENEMY_IDLE_DOWN,
	ENEMY_IDLE_LEFT,
	ENEMY_IDLE_RIGHT,
	ENEMY_WALK_UP,
	ENEMY_WALK_DOWN,
	ENEMY_WALK_LEFT,
	ENEMY_WALK_RIGHT,
	ENEMY_ATTACK_UP,
	NUM_OF_ENEMY_ANIMATION_STATES
};

#endif